// src/webui/FE/components/QQLogin.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { ArrowDown, RefreshCw, X, Loader2 } from 'lucide-react';
import { apiFetch } from '../utils/api';
import { SelfInfo } from '../types';
import { showToast } from './Toast';

interface Account {
  uin: string;
  uid: string;
  nickName?: string;
  faceUrl: string;
  loginType: number;
  isQuickLogin: boolean;
  isAutoLogin: boolean;
}

interface QRCodeData {
  pngBase64QrcodeData: string;
  qrcodeUrl: string;
  expireTime: number;
  pollTimeInterval: number;
}

interface QuickLoginResult {
  result: string;
  loginErrorInfo: {
    errMsg: string;
  };
}

interface GetLoginListResult {
  LocalLoginInfoList: Account[];
}

interface QQLoginProps {
  onLoginSuccess: () => void;
}

const QQLogin: React.FC<QQLoginProps> = ({ onLoginSuccess }) => {
  const [loginMode, setLoginMode] = useState<'quick' | 'qr'>('quick');
  const [showAccountList, setShowAccountList] = useState(false);
  const [loginLoading, setLoginLoading] = useState(false);
  const [qrExpired, setQrExpired] = useState(false);
  const [qrStatus, setQrStatus] = useState<'scanning' | 'success' | 'expired' | 'error' | ''>('');

  const [accounts, setAccounts] = useState<Account[]>([]);
  const [selectedAccount, setSelectedAccount] = useState<Account | null>(null);
  const [showRemoveAccount, setShowRemoveAccount] = useState(false);

  const qrCanvasRef = useRef<HTMLCanvasElement>(null);
  const qrRefreshIntervalRef = useRef<NodeJS.Timeout | null>(null);
  const loginPollingIntervalRef = useRef<NodeJS.Timeout | null>(null);
  const isPollingLoginRef = useRef(false);

  const qrStatusText = {
    scanning: '扫描成功，请在手机上确认',
    success: '登录成功',
    expired: '二维码已过期，请刷新',
    error: '登录失败，请重试',
    '': '',
  };

  // 停止轮询登录状态
  const stopLoginPolling = useCallback(() => {
    isPollingLoginRef.current = false;
    if (loginPollingIntervalRef.current) {
      clearTimeout(loginPollingIntervalRef.current);
      loginPollingIntervalRef.current = null;
    }
  }, []);

  // 轮询登录状态
  const pollLoginStatus = useCallback(async () => {
    if (isPollingLoginRef.current) {
      return;
    }

    isPollingLoginRef.current = true;
    console.log('开始轮询登录状态...');

    const maxAttempts = 60; // 最多轮询60次（约5分钟）
    let attempts = 0;

    const poll = async () => {
      if (attempts >= maxAttempts) {
        stopLoginPolling();
        showToast('登录超时，请重试', 'error');
        if (loginMode === 'qr') {
          setQrStatus('error');
        }
        return;
      }

      attempts++;

      try {
        const result = await apiFetch<SelfInfo>('/api/login-info');
        if (result.success && result.data.online === true) {
          stopLoginPolling();
          showToast('登录成功！正在跳转到主页面...', 'success');
          if (loginMode === 'qr') {
            setQrStatus('success');
          }
          setTimeout(() => {
            onLoginSuccess();
          }, 1000);
          return;
        }

        // 继续轮询
        loginPollingIntervalRef.current = setTimeout(poll, 3000); // 每3秒轮询一次
      } catch (error: any) {
        console.warn('轮询登录状态失败:', error);
        // 继续轮询，不中断
        loginPollingIntervalRef.current = setTimeout(poll, 3000);
      }
    };

    // 开始第一次轮询
    await poll();
  }, [loginMode, onLoginSuccess, stopLoginPolling]);

  // 显示二维码
  const displayQrCode = useCallback((base64Data: string) => {
    if (!qrCanvasRef.current) return;

    const canvas = qrCanvasRef.current;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const img = new Image();
    img.onload = () => {
      ctx.clearRect(0, 0, 200, 200);
      ctx.drawImage(img, 0, 0, 200, 200);
    };
    img.src = base64Data;
  }, []);

  // 生成二维码
  const generateQrCode = useCallback(async () => {
    if (!qrCanvasRef.current) return;

    try {
      const result = await apiFetch<QRCodeData>('/api/login-qrcode');

      if (result.success && result.data) {
        displayQrCode(result.data.pngBase64QrcodeData);

        // 设置过期定时器
        const expireTime = result.data.expireTime * 1000;
        if (qrRefreshIntervalRef.current) {
          clearInterval(qrRefreshIntervalRef.current);
        }
        qrRefreshIntervalRef.current = setTimeout(() => {
          setQrExpired(true);
          setQrStatus('expired');
          stopLoginPolling();
        }, expireTime);

        setQrExpired(false);
        setQrStatus('');

        showToast('请使用手机QQ扫码登录', 'warning');
        await pollLoginStatus();
      } else {
        throw new Error(result.message || '获取二维码失败');
      }
    } catch (error: any) {
      showToast(error.message || '获取二维码失败', 'error');
      console.error('QR code generation error:', error);
    }
  }, [displayQrCode, pollLoginStatus, stopLoginPolling]);

  // 刷新二维码
  const refreshQrCode = useCallback(async () => {
    await generateQrCode();
    showToast('二维码已刷新', 'success');
  }, [generateQrCode]);

  // 获取快速登录列表（防重复：通过 hasFetchedRef 控制）
  const hasFetchedRef = useRef(false);
  const fetchQuickLoginList = useCallback(async () => {
    if (hasFetchedRef.current) return;
    hasFetchedRef.current = true;
    try {
      const result = await apiFetch<GetLoginListResult>('/api/quick-login-list');
      console.log('Quick login list response:', result);

      if (result.success && result.data && result.data.LocalLoginInfoList) {
        const quickLoginAccounts = result.data.LocalLoginInfoList.filter(item => item.isQuickLogin);
        setAccounts(quickLoginAccounts);
        console.log('Accounts loaded:', quickLoginAccounts);

        if (quickLoginAccounts.length > 0) {
          // 仅在还未选择账号时设置，避免触发依赖循环
          setSelectedAccount(prev => prev ?? quickLoginAccounts[0]);
        } else {
          setLoginMode('qr');
        }
      } else {
        console.warn('No quick login accounts available:', result.message);
        setAccounts([]);
      }
    } catch (error: any) {
      console.error('Failed to fetch quick login list:', error);
      showToast('获取快速登录列表失败', 'error');
      setAccounts([]);
    }
  }, []);

  // 快速登录
  const handleQuickLogin = useCallback(async () => {
    if (!selectedAccount) return;

    setLoginLoading(true);
    try {
      const resp = await apiFetch<QuickLoginResult>('/api/quick-login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ uin: selectedAccount.uin }),
      });
      const data = resp.data;
      if (data.result === '0') {
        showToast(`正在登录 ${selectedAccount.nickName}...`, 'success');
        await pollLoginStatus();
      } else {
        throw new Error(data.loginErrorInfo.errMsg || '登录失败');
      }
    } catch (error: any) {
      showToast(error.message, 'error');
      console.error('Quick login error:', error);
      setLoginMode('qr');
    } finally {
      setLoginLoading(false);
    }
  }, [selectedAccount, pollLoginStatus]);

  // 切换账号列表显示
  const toggleAccountList = () => {
    setShowAccountList(!showAccountList);
  };

  // 选择账号
  const selectAccount = (account: Account) => {
    setSelectedAccount(account);
    setShowAccountList(false);
  };

  // 移除账号
  const removeAccount = (uin: string) => {
    const index = accounts.findIndex(acc => acc.uin === uin);
    if (index > -1) {
      const removedAccount = accounts.splice(index, 1)[0];
      const newAccounts = [...accounts];
      setAccounts(newAccounts);

      if (selectedAccount?.uin === uin && newAccounts.length > 0) {
        setSelectedAccount(newAccounts[0]);
      } else if (selectedAccount?.uin === uin) {
        setSelectedAccount(null);
      }
      showToast(`已移除账号 ${removedAccount.nickName}`, 'success');
    }
    setShowRemoveAccount(false);
  };

  // 初始化
  useEffect(() => {
    if (!hasFetchedRef.current) fetchQuickLoginList();

    return () => {
      if (qrRefreshIntervalRef.current) {
        clearInterval(qrRefreshIntervalRef.current);
      }
      stopLoginPolling();
    };
  }, []);

  // 监听登录模式变化
  useEffect(() => {
    if (loginMode === 'qr') {
      setTimeout(() => generateQrCode(), 100);
    } else if (qrRefreshIntervalRef.current) {
      clearInterval(qrRefreshIntervalRef.current);
    }

    // 当从二维码模式切换到快速登录且还未获取过列表时再获取，避免重复
    if (loginMode === 'quick' && accounts.length === 0 && !hasFetchedRef.current) {
      fetchQuickLoginList();
    }
  }, [loginMode, accounts.length, generateQrCode]);

  return (
    <div className="relative min-h-screen flex flex-col items-center justify-center p-5">
      {/* Login Content - AnimatedBackground now provided by App.tsx */}
      <div className="bg-white/50 backdrop-blur-2xl rounded-3xl p-10 shadow-xl border border-white/30 min-w-[320px] text-center relative z-10">
        {/* Quick Login Mode */}
        {loginMode === 'quick' && (
          <div className="flex flex-col items-center gap-6">
            {/* Single Account Display */}
            {!showAccountList && selectedAccount && (
              <div
                className="flex flex-col items-center cursor-pointer p-4 rounded-2xl transition-colors hover:bg-blue-50"
                onClick={toggleAccountList}
              >
                <div className="w-20 h-20 rounded-full overflow-hidden mb-3 shadow-lg">
                  <img src={selectedAccount.faceUrl} alt={selectedAccount.nickName} className="w-full h-full object-cover" />
                </div>
                <div className="text-base text-gray-800 mb-2">{selectedAccount.nickName}</div>
              </div>
            )}

            {/* Account List */}
            {showAccountList && (
              <div className="grid grid-cols-2 gap-4 my-5 w-full max-w-md">
                {accounts.map((account) => (
                  <div
                    key={account.uin}
                    className="flex flex-col items-center p-4 rounded-2xl cursor-pointer transition-all border-2 border-transparent hover:bg-blue-50 hover:border-blue-500"
                    onClick={() => selectAccount(account)}
                  >
                    <div className="w-[60px] h-[60px] rounded-full overflow-hidden mb-2 shadow-md">
                      <img src={account.faceUrl} alt={account.nickName} className="w-full h-full object-cover" />
                    </div>
                    <div className="text-sm text-gray-800 text-center truncate w-full px-1">{account.nickName}</div>
                  </div>
                ))}
              </div>
            )}

            {/* Login Button */}
            {!showAccountList && (
              <button
                onClick={handleQuickLogin}
                disabled={!selectedAccount || loginLoading}
                className="w-[280px] h-11 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-full font-medium text-base disabled:opacity-50 disabled:cursor-not-allowed hover:shadow-lg transition-all flex items-center justify-center gap-2"
              >
                {loginLoading ? (
                  <>
                    <Loader2 size={20} className="animate-spin" />
                    登录中...
                  </>
                ) : (
                  '登录'
                )}
              </button>
            )}

            {/* Action Links */}
            <div className="flex gap-6">
              <button onClick={() => setLoginMode('qr')} className="text-blue-600 text-sm hover:underline">
                扫码登录
              </button>
              {/* 暂时注释掉移除账号功能 */}
              {/* <button onClick={() => setShowRemoveAccount(true)} className="text-blue-600 text-sm hover:underline">
                移除账号
              </button> */}
            </div>
          </div>
        )}

        {/* QR Code Login Mode */}
        {loginMode === 'qr' && (
          <div className="flex flex-col items-center gap-5">
            <div className="relative inline-block">
              <div className="relative p-5 bg-white rounded-2xl shadow-lg">
                <canvas ref={qrCanvasRef} width="200" height="200" className="block rounded-lg" />

                {/* QR Refresh Overlay */}
                {qrExpired && (
                  <div
                    className="absolute inset-0 bg-black/70 flex flex-col items-center justify-center text-white cursor-pointer rounded-2xl transition-opacity hover:opacity-90"
                    onClick={refreshQrCode}
                  >
                    <RefreshCw size={32} className="mb-2" />
                    <div>点击刷新</div>
                  </div>
                )}
              </div>
            </div>

            <div className="text-gray-600">请使用手机QQ扫码登录</div>

            {/* QR Status Messages */}
            {qrStatus && (
              <div
                className={`text-sm px-4 py-2 rounded-lg ${
                  qrStatus === 'success'
                    ? 'bg-green-100 text-green-800'
                    : qrStatus === 'error' || qrStatus === 'expired'
                    ? 'bg-red-100 text-red-800'
                    : 'bg-blue-100 text-blue-800'
                }`}
              >
                {qrStatusText[qrStatus]}
              </div>
            )}
          </div>
        )}

        {/* Mode Switch */}
        <div className="mt-6">
          {loginMode === 'qr' && accounts.length > 0 && (
            <button onClick={() => setLoginMode('quick')} className="text-blue-600 text-sm hover:underline">
              快速登录
            </button>
          )}
        </div>
      </div>

      {/* Remove Account Dialog - 暂时注释掉 */}
      {/* {showRemoveAccount && (
        <div className="fixed inset-0 bg-black/30 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-3xl shadow-2xl w-full max-w-md p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-xl font-semibold text-gray-900">移除账号</h3>
              <button onClick={() => setShowRemoveAccount(false)} className="text-gray-400 hover:text-gray-600">
                <X size={24} />
              </button>
            </div>
            
            <div className="mb-4 text-sm text-gray-600">选择要移除的账号:</div>
            
            <div className="space-y-2 max-h-96 overflow-y-auto">
              {accounts.map((account) => (
                <div
                  key={account.uin}
                  className="flex items-center gap-3 p-3 rounded-xl cursor-pointer hover:bg-gray-100 transition-colors"
                  onClick={() => removeAccount(account.uin)}
                >
                  <img src={account.faceUrl} alt={account.nickName} className="w-10 h-10 rounded-full" />
                  <span className="flex-1 text-gray-800">{account.nickName}</span>
                  <X size={20} className="text-red-500" />
                </div>
              ))}
            </div>
            
            <div className="mt-6 flex justify-end">
              <button
                onClick={() => setShowRemoveAccount(false)}
                className="px-6 py-2 bg-gray-200 text-gray-700 rounded-xl hover:bg-gray-300 transition-colors"
              >
                取消
              </button>
            </div>
          </div>
        </div>
      )} */}
    </div>
  );
};

export default QQLogin;

// src/webui/FE/components/QQLogin.vue
<template>
  <div class='qq-login-container'>
    <!-- QQ Logo -->
    <div class='login-content'>
      <!-- Quick Login Mode -->
      <div v-if="loginMode === 'quick'" class='quick-login'>
        <!-- Single Account Display -->
        <div v-if='!showAccountList && selectedAccount' class='account-display' @click='toggleAccountList'>
          <div class='account-avatar'>
            <img :src='selectedAccount.faceUrl' :alt='selectedAccount.nickName' />
          </div>
          <div class='account-name'>{{ selectedAccount.nickName }}</div>
          <el-icon v-if='accounts.length > 1' class='dropdown-icon' :class='{ rotated: showAccountList }'>
            <ArrowDown />
          </el-icon>
        </div>

        <!-- Account List -->
        <div v-else class='account-list'>
          <div
            v-for='account in accounts'
            :key='account.uin'
            class='account-item'
            @click='selectAccount(account)'
          >
            <div class='account-avatar'>
              <img :src='account.faceUrl' :alt='account.nickName' />
            </div>
            <div class='account-name'>{{ account.nickName }}</div>
          </div>
        </div>

        <!-- Login Button -->
        <el-button
          v-if='!showAccountList'
          type='primary'
          size='large'
          class='login-button'
          :loading='loginLoading'
          :disabled='!selectedAccount'
          @click='handleQuickLogin'
        >
          登录
        </el-button>

        <!-- Action Links -->
        <div class='action-links'>
          <el-link @click="loginMode = 'qr'">扫码登录</el-link>
          <el-link @click='showRemoveAccount = true'>移除账号</el-link>
        </div>
      </div>

      <!-- QR Code Login Mode -->
      <div v-else class='qr-login'>
        <div class='qr-code-container'>
          <div class='qr-code'>
            <!-- QR Code placeholder - replace with actual QR code -->
            <canvas ref='qrCanvas' width='200' height='200'></canvas>
            <!-- QR Code refresh overlay if expired -->
            <div v-if='qrExpired' class='qr-refresh-overlay' @click='refreshQrCode'>
              <el-icon>
                <Refresh />
              </el-icon>
              <div>点击刷新</div>
            </div>
          </div>
          <!-- QQ Penguin Logo in center -->
          <!--          <div class="qr-center-logo">-->
          <!--            <div class="penguin-icon">🐧</div>-->
          <!--          </div>-->
        </div>
        <div class='qr-tip'>请使用手机QQ扫码登录</div>

        <!-- QR Status Messages -->
        <div v-if='qrStatus' class='qr-status' :class='qrStatusClass'>
          {{ qrStatusText }}
        </div>
      </div>

      <!-- Mode Switch Links -->
      <div class='mode-switch'>
        <el-link
          v-if="loginMode === 'qr'"
          @click="loginMode = 'quick'"
          class='switch-link'
        >
          快速登录
        </el-link>
      </div>
    </div>
    <!-- Remove Account Dialog -->
    <el-dialog v-model='showRemoveAccount' title='移除账号' width='400px'>
      <div>选择要移除的账号:</div>
      <div class='remove-account-list'>
        <div
          v-for='account in accounts'
          :key='account.uin'
          class='remove-account-item'
          @click='removeAccount(account.uin)'
        >
          <img :src='account.faceUrl' :alt='account.nickName' class='small-avatar' />
          <span>{{ account.nickName }}</span>
          <el-icon class='remove-icon'>
            <Close />
          </el-icon>
        </div>
      </div>
      <template #footer>
        <el-button @click='showRemoveAccount = false'>取消</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang='ts'>
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import { ElMessage } from 'element-plus'
import { ArrowDown, Refresh, Close } from '@element-plus/icons-vue'
import { apiGet, apiPost, getToken } from '../utils/api'
import {
  GetLoginListResult,
  OnQRCodeLoginSucceedParameter,
  QuickLoginResult,
} from '../../../ntqqapi/services/NodeIKernelLoginService'
import { SelfInfo } from '../../../ntqqapi/types'

// Define emits
const emit = defineEmits<{
  login: [loginData: { mode: 'quick' | 'qr', account?: Account }]
}>()

interface Account {
  uin: string
  uid: string
  nickName?: string
  faceUrl: string
  loginType: number
  isQuickLogin: boolean
  isAutoLogin: boolean
}

interface QRCodeData {
  pngBase64QrcodeData: string
  qrcodeUrl: string
  expireTime: number
  pollTimeInterval: number
}

const loginMode = ref<'quick' | 'qr'>('quick')
const showAccountList = ref(false)
const loginLoading = ref(false)
const qrExpired = ref(false)
const qrStatus = ref('')
const qrStatusClass = ref('')

// Account management
const accounts = ref<Account[]>([])
const qrCodeData = ref<QRCodeData | null>(null)

const selectedAccount = ref<Account | null>(null)
const showRemoveAccount = ref(false)

// QR Code related
const qrCanvas = ref<HTMLCanvasElement>()
let qrRefreshInterval: NodeJS.Timeout | null = null

// Login polling related
let loginPollingInterval: NodeJS.Timeout | null = null
const isPollingLogin = ref(false)

const qrStatusText = computed(() => {
  switch (qrStatus.value) {
    case 'scanning':
      return '扫描成功，请在手机上确认'
    case 'success':
      return '登录成功'
    case 'expired':
      return '二维码已过期，请刷新'
    case 'error':
      return '登录失败，请重试'
    default:
      return ''
  }
})

function toggleAccountList() {
  showAccountList.value = !showAccountList.value
}

function selectAccount(account: Account) {
  selectedAccount.value = account
  showAccountList.value = false
}

async function handleQuickLogin() {
  if (!selectedAccount.value) return

  loginLoading.value = true
  try {
    const resp = await apiPost<QuickLoginResult>('/api/quick-login', { uin: selectedAccount.value.uin })
    const data = resp.data
    if (data.result === '0') {
      ElMessage.info(`正在登录 ${selectedAccount.value.nickName}...`)
      // 开始轮询登录状态
      await pollLoginStatus()
    }
    else {
      throw new Error(data.loginErrorInfo.errMsg || '登录失败')
    }
  } catch (error: any) {
    ElMessage.error(error.message)
    console.error('Quick login error:', error)
    loginMode.value = 'qr'
  } finally {
    loginLoading.value = false
  }
}

function removeAccount(uin: string) {
  const index = accounts.value.findIndex(acc => acc.uin === uin)
  if (index > -1) {
    const removedAccount = accounts.value.splice(index, 1)[0]
    if (selectedAccount.value?.uin === uin && accounts.value.length > 0) {
      selectedAccount.value = accounts.value[0]
    }
    else if (selectedAccount.value?.uin === uin) {
      selectedAccount.value = null
    }
    ElMessage.success(`已移除账号 ${removedAccount.nickName}`)
  }
  showRemoveAccount.value = false
}

async function generateQrCode() {
  if (!qrCanvas.value) return

  try {
    const result = await apiGet<OnQRCodeLoginSucceedParameter>('/api/login-qrcode')

    if (result.success && result.data) {
      qrCodeData.value = result.data
      displayQrCode(result.data.pngBase64QrcodeData)

      // Set expiration timer based on server response
      const expireTime = result.data.expireTime * 1000 // Convert to milliseconds
      if (qrRefreshInterval) {
        clearInterval(qrRefreshInterval)
      }
      qrRefreshInterval = setTimeout(() => {
        qrExpired.value = true
        qrStatus.value = 'expired'
        stopLoginPolling() // 停止轮询，因为二维码已过期
      }, expireTime)

      qrExpired.value = false
      qrStatus.value = ''

      // 二维码生成成功后，开始轮询登录状态
      ElMessage.info('请使用手机QQ扫码登录')
      await pollLoginStatus()
    }
    else {
      throw new Error(result.message || '获取二维码失败')
    }
  } catch (error: any) {
    ElMessage.error(error.message || '获取二维码失败')
    console.error('QR code generation error:', error)
    // Fallback to placeholder pattern
    displayPlaceholderQrCode()
  }
}

function displayQrCode(base64Data: string) {
  if (!qrCanvas.value) return

  const canvas = qrCanvas.value
  const ctx = canvas.getContext('2d')
  if (!ctx) return

  const img = new Image()
  img.onload = () => {
    ctx.clearRect(0, 0, 200, 200)
    ctx.drawImage(img, 0, 0, 200, 200)
  }
  img.src = base64Data
}

function displayPlaceholderQrCode() {
  if (!qrCanvas.value) return

  const canvas = qrCanvas.value
  const ctx = canvas.getContext('2d')
  if (!ctx) return

  // Simple QR code pattern simulation
  ctx.fillStyle = '#000'
  ctx.fillRect(0, 0, 200, 200)
  ctx.fillStyle = '#fff'

  // Create a simple dot pattern to simulate QR code
  for (let i = 0; i < 20; i++) {
    for (let j = 0; j < 20; j++) {
      if (Math.random() > 0.5) {
        ctx.fillRect(i * 10, j * 10, 10, 10)
      }
    }
  }
}

async function refreshQrCode() {
  await generateQrCode()
  ElMessage.info('二维码已刷新')
}

async function fetchQuickLoginList() {
  try {
    const result = await apiGet<GetLoginListResult>('/api/quick-login-list')
    console.log('Quick login list response:', result)

    if (result.success && result.data && result.data.LocalLoginInfoList) {
      accounts.value = result.data.LocalLoginInfoList.filter(item => item.isQuickLogin)
      console.log('Accounts loaded:', accounts.value)

      if (accounts.value.length > 0 && !selectedAccount.value) {
        selectedAccount.value = accounts.value[0]
      }
      else {
        loginMode.value = 'qr'
      }
    }
    else {
      console.warn('No quick login accounts available:', result.message)
      accounts.value = []
    }
  } catch (error: any) {
    console.error('Failed to fetch quick login list:', error)
    ElMessage.error('获取快速登录列表失败')
    accounts.value = []
  }
}

// 轮询login-info接口检查登录状态
async function pollLoginStatus(): Promise<void> {
  if (isPollingLogin.value) {
    return
  }

  isPollingLogin.value = true
  console.log('开始轮询登录状态...')

  const maxAttempts = 60 // 最多轮询60次（约5分钟）
  let attempts = 0

  const poll = async () => {
    if (attempts >= maxAttempts) {
      stopLoginPolling()
      ElMessage.warning('登录超时，请重试')
      if (loginMode.value === 'qr') {
        qrStatus.value = 'error'
      }
      return
    }

    attempts++

    try {
      const result = await apiGet<SelfInfo>('/api/login-info')
      const data = result.data
      if (result.success && data.online === true) {
        stopLoginPolling()
        ElMessage.success('登录成功！正在跳转到主页面...')
        if (loginMode.value === 'qr') {
          qrStatus.value = 'success'
        }
        setTimeout(() => {
          // 刷新页面
          window.location.reload()
        }, 1000)
      }

      // 延迟一下让用户看到成功消息
      // setTimeout(() => {
      //   emitLogin(loginMode.value, selectedAccount.value || undefined)
      // }, 1000)
      // 继续轮询
      loginPollingInterval = setTimeout(poll, 3000) // 每3秒轮询一次

    } catch (error: any) {
      console.warn('轮询登录状态失败:', error)
      // 继续轮询，不中断
      loginPollingInterval = setTimeout(poll, 3000)
    }
  }

  // 开始第一次轮询
  await poll()
}

// 停止轮询登录状态
function stopLoginPolling(): void {
  isPollingLogin.value = false
  if (loginPollingInterval) {
    clearTimeout(loginPollingInterval)
    loginPollingInterval = null
  }
}

function emitLogin(mode: 'quick' | 'qr', account?: Account) {
  // Emit login event to parent component
  console.log('Login attempt:', { mode, account })
  emit('login', { mode, account })
}

onMounted(async () => {
  // Fetch quick login list first
  await fetchQuickLoginList()

  // Generate QR code if in QR mode
  if (loginMode.value === 'qr') {
    await generateQrCode()
  }
})

onUnmounted(() => {
  if (qrRefreshInterval) {
    clearInterval(qrRefreshInterval)
  }
  // 清理轮询定时器
  stopLoginPolling()
})

// Watch login mode changes
watch(loginMode, async (newMode) => {
  if (newMode === 'qr') {
    setTimeout(() => generateQrCode(), 100) // Delay to ensure canvas is ready
  }
  else if (qrRefreshInterval) {
    clearInterval(qrRefreshInterval)
  }

  if (newMode === 'quick' && accounts.value.length === 0) {
    await fetchQuickLoginList()
  }
})

// Close account list when clicking outside
function handleClickOutside(event: Event) {
  const target = event.target as HTMLElement
  if (!target.closest('.account-display') && !target.closest('.account-list')) {
    showAccountList.value = false
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
})
</script>

<style scoped>
.qq-login-container {
  min-height: 100vh;
  background: linear-gradient(135deg, #e8f4fd 0%, #d4edff 50%, #c8e8ff 100%);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 20px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.qq-logo {
  margin-bottom: 40px;
}

.qq-icon {
  width: 80px;
  height: 80px;
  color: #1890ff;
}

.login-content {
  background: rgba(255, 255, 255, 0.9);
  backdrop-filter: blur(10px);
  border-radius: 20px;
  padding: 40px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
  min-width: 320px;
  text-align: center;
}

/* Quick Login Styles */
.quick-login {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 24px;
}

.account-display {
  display: flex;
  flex-direction: column;
  align-items: center;
  cursor: pointer;
  padding: 16px;
  border-radius: 12px;
  transition: background-color 0.2s;
}

.account-display:hover {
  background-color: rgba(24, 144, 255, 0.05);
}

.account-avatar {
  width: 80px;
  height: 80px;
  border-radius: 50%;
  overflow: hidden;
  margin-bottom: 12px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.account-avatar img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.account-name {
  font-size: 16px;
  color: #333;
  margin-bottom: 8px;
}

.dropdown-icon {
  font-size: 16px;
  color: #666;
  transition: transform 0.2s;
}

.dropdown-icon.rotated {
  transform: rotate(180deg);
}

.account-list {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 16px;
  margin: 20px 0;
}

.account-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 16px;
  border-radius: 12px;
  cursor: pointer;
  transition: all 0.2s;
  border: 2px solid transparent;
}

.account-item:hover {
  background-color: rgba(24, 144, 255, 0.05);
  border-color: #1890ff;
}

.account-item .account-avatar {
  width: 60px;
  height: 60px;
  margin-bottom: 8px;
}

.account-item .account-name {
  font-size: 14px;
  margin-bottom: 0;
}

.login-button {
  width: 280px;
  height: 44px;
  border-radius: 22px;
  font-size: 16px;
  font-weight: 500;
}

.action-links {
  display: flex;
  gap: 24px;
}

.action-links .el-link {
  font-size: 14px;
}

/* QR Login Styles */
.qr-login {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 20px;
}

.qr-code-container {
  position: relative;
  display: inline-block;
}

.qr-code {
  position: relative;
  padding: 20px;
  background: white;
  border-radius: 12px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.qr-code canvas {
  display: block;
  border-radius: 8px;
}

.qr-refresh-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.7);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  color: white;
  cursor: pointer;
  border-radius: 12px;
  transition: opacity 0.2s;
}

.qr-refresh-overlay:hover {
  opacity: 0.9;
}

.qr-refresh-overlay .el-icon {
  font-size: 32px;
  margin-bottom: 8px;
}

.qr-center-logo {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 40px;
  height: 40px;
  background: white;
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.penguin-icon {
  font-size: 24px;
}

.qr-tip {
  font-size: 16px;
  color: #666;
}

.qr-status {
  font-size: 14px;
  padding: 8px 16px;
  border-radius: 6px;
}

.qr-status.scanning {
  background: #e6f7ff;
  color: #1890ff;
}

.qr-status.success {
  background: #f6ffed;
  color: #52c41a;
}

.qr-status.expired,
.qr-status.error {
  background: #fff2f0;
  color: #ff4d4f;
}

.mode-switch {
  margin-top: 24px;
  padding-top: 20px;
  border-top: 1px solid #f0f0f0;
}

.switch-link {
  font-size: 14px;
  color: #1890ff;
}

/* Dialog Styles */
.remove-account-list {
  margin: 16px 0;
}

.remove-account-item {
  display: flex;
  align-items: center;
  padding: 12px;
  border-radius: 8px;
  cursor: pointer;
  transition: background-color 0.2s;
  gap: 12px;
}

.remove-account-item:hover {
  background-color: #f5f5f5;
}

.small-avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  object-fit: cover;
}

.remove-icon {
  margin-left: auto;
  color: #ff4d4f;
}

/* Responsive Design */
@media (max-width: 480px) {
  .login-content {
    padding: 24px;
    min-width: 280px;
  }

  .account-list {
    grid-template-columns: 1fr;
  }

  .login-button {
    width: 240px;
  }
}
</style>
