// src/webui/FE/App.vue
<template>
  <el-container class='main-container'>
    <el-header class='header'>
      <h2 style='display:inline-block;'>LLTwoBot {{version}}</h2>
    </el-header>
    <el-main v-loading='loading'>
      <el-row :gutter='24' justify='center'>
        <el-col :xs='24' :sm='22' :md='20' :lg='16' :xl='12'>
          <el-card shadow='hover' class='config-card'>
            <AccountInfo :accountNick='accountNick' :accountUin='accountUin' />
            <el-menu mode='horizontal' :default-active='activeIndex' @select='handleSelect'>
              <el-menu-item index='1'>OneBot 11 配置</el-menu-item>
              <el-menu-item index='2'>Satori 配置</el-menu-item>
              <el-menu-item index='3'>其他配置</el-menu-item>
              <el-menu-item index='4'>关于</el-menu-item>
            </el-menu>
            <el-form :model='form' label-width='160px' size='large' class='config-form'>
              <Ob11ConfigForm
                ref='ob11ConfigFormRef'
                v-if="activeIndex === '1'"
                v-model='form.ob11'
              />
              <SatoriConfigForm v-if="activeIndex === '2'" v-model='form.satori' />
              <OtherConfigForm v-if="activeIndex === '3'" v-model='form' />
              <About v-if="activeIndex === '4'" />
              <el-form-item class='form-actions' v-if="activeIndex != '4'">
                <el-button type='primary' @click='onSave' size='large' style='float: right;' :loading='loading'>
                  保存配置
                </el-button>
              </el-form-item>
            </el-form>
          </el-card>
        </el-col>
      </el-row>
    </el-main>
    <TokenDialog v-model:visible='showTokenDialog' v-model:tokenInput='tokenInput' :loading='tokenDialogLoading'
                 :error='tokenDialogError' @confirm='handleTokenDialogConfirm' @close='handleTokenDialogClose' />
  </el-container>
</template>

<script setup lang='ts'>
import { ref, onMounted, watch, nextTick } from 'vue'
import { ElMessage, ElDialog, ElInput, ElButton } from 'element-plus'
import { QuestionFilled } from '@element-plus/icons-vue'
import AccountInfo from './components/AccountInfo.vue'
import Ob11ConfigForm from './components/Ob11ConfigForm.vue'
import SatoriConfigForm from './components/SatoriConfigForm.vue'
import OtherConfigForm from './components/OtherConfigForm.vue'
import TokenDialog from './components/TokenDialog.vue'
import { Config } from '@common/types'
import { version } from '../../version'
import About from '@/components/About.vue'
import './App.css'

// Token logic
const tokenKey = 'webui_token'
const token = ref(localStorage.getItem(tokenKey) || '')
const showTokenDialog = ref(false)
const tokenInput = ref('')
const tokenDialogLoading = ref(false)
const tokenDialogError = ref('')

const defaultConfig: Config = {
  satori: { enable: false, port: 5600, token: '' },
  ob11: {
    enable: true,
    token: '',
    httpPort: 3000,
    httpPostUrls: [],
    httpSecret: '',
    wsPort: 3001,
    wsReverseUrls: [],
    enableHttp: true,
    enableHttpPost: true,
    enableWs: true,
    enableWsReverse: false,
    messagePostFormat: 'array',
    enableHttpHeart: false,
    reportSelfMessage: true,
  },
  heartInterval: 60000,
  enableLocalFile2Url: false,
  debug: false,
  log: true,
  autoDeleteFile: false,
  autoDeleteFileSecond: 60,
  musicSignUrl: '',
  msgCacheExpire: 120,
  onlyLocalhost: true,
  webui: {
    enable: true,
    token: '',
    port: 3080,
  },
  receiveOfflineMsg: false
}

const form = ref(JSON.parse(JSON.stringify(defaultConfig)))
const activeIndex = ref('1')
const loading = ref(false)
const accountNick = ref('')
const accountUin = ref('')

const ob11ConfigFormRef = ref()

async function setToken(newToken: string) {
  // 先请求后端
  try {
    const resp = await fetch('/api/set-token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ token: newToken }),
    })
    const data = await resp.json()
    if (!data.success) {
      throw new Error(data.message || '设置密码失败')
    }
    token.value = newToken
    localStorage.setItem(tokenKey, newToken)
    ElMessage.success('密码设置成功')
  } catch (e: any) {
    ElMessage.error(e.message || '设置密码失败')
    throw e
  }
}

// 弹出密码输入框，直到用户输入非空密码并点击确定/回车才resolve
async function promptPassword(tip: string): Promise<string> {

  return new Promise<string>((resolve) => {
    tokenDialogError.value = ''
    tokenInput.value = ''
    showTokenDialog.value = true
    tokenDialogError.value = tip

    async function onConfirm() {
      const pwd = tokenInput.value.trim()
      if (!pwd) {
        tokenDialogError.value = '密码不能为空'
        return
      }
      showTokenDialog.value = false
      resolve(pwd)
    }

    // 监听弹窗关闭（防止用户点ESC或X关闭）
    const stopShow = watch(showTokenDialog, (val) => {
      if (!val) {
        stopShow()

      }
    })
    // 监听确定按钮
    handleTokenDialogConfirm = onConfirm
  })
}

// 包装 fetch，自动带 token
async function apiFetch(url: string, options: any = {}): Promise<Response> {
  options.headers = options.headers || {}
  if (token.value) {
    options.headers['x-webui-token'] = token.value
  }
  let resp = await fetch(url, options)
  // 如果不是401/403，直接返回
  if (resp.status !== 401 && resp.status !== 403) {
    return resp
  }
  while (resp.status === 401 || resp.status === 403) {
    if (resp.status === 401) {
      token.value = ''
      localStorage.removeItem(tokenKey)
      const inputPwd = await promptPassword('请设置密码')
      // 401时需要setToken
      try {
        await setToken(inputPwd)
      } catch {
        throw new Error('设置密码失败')
      }
      tokenInput.value = ''
    }
    else if (resp.status === 403) {
      token.value = ''
      localStorage.removeItem(tokenKey)
      const inputPwd = await promptPassword('密码校验失败，请输入密码')
      // 403时只保存本地密码，不调用setToken
      token.value = inputPwd
      localStorage.setItem(tokenKey, token.value)
      tokenInput.value = ''
    }
    // 重新带新密码请求
    options.headers['x-webui-token'] = token.value
    resp = await fetch(url, options)
    if (resp.status !== 401 && resp.status !== 403) {
      return resp
    }
  }
  return resp
}


// 获取配置
async function fetchConfig() {
  try {
    loading.value = true
    const resp = await apiFetch('/api/config')
    const data = await resp.json()
    if (data.success) {
      // 兼容新格式
      if (data.data.config && data.data.selfInfo) {
        form.value = data.data.config
        accountNick.value = data.data.selfInfo.nick || ''
        accountUin.value = data.data.selfInfo.uin || ''
      }
      else {
        form.value = data.data
        accountNick.value = ''
        accountUin.value = ''
      }
      console.log('config接口返回:', data)
      ElMessage.success('配置加载成功')
    }
    else {
      throw new Error(data.message || '获取配置失败')
    }
  } catch (error: any) {
    ElMessage.error(`获取配置失败: ${error.message || String(error)}`)
    console.error('获取配置失败:', error)
  } finally {
    loading.value = false
  }
}

// 保存配置
async function onSave() {
  if (ob11ConfigFormRef.value && !ob11ConfigFormRef.value.saveInputting()) {
    return
  }
  if (!form.value.webui.token) {
    return ElMessage.error('WebUI 密码不能为空')
  }
  try {
    loading.value = true
    const resp = await apiFetch('/api/config', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(form.value),
    })
    const data = await resp.json()
    if (data.success) {
      localStorage.setItem(tokenKey, form.value.webui.token)
      token.value = form.value.webui.token
      ElMessage.success('配置保存成功')
    }
    else {
      throw new Error(data.message || '保存配置失败')
    }
  } catch (error: any) {
    ElMessage.error(`保存配置失败: ${error.message || String(error)}`)
    console.error('保存配置失败:', error)
  } finally {
    loading.value = false
  }
}

// 页面加载时获取配置
onMounted(() => {
  fetchConfig()
})


function handleSelect(key: string) {
  activeIndex.value = key
}

// 修改handleTokenDialogConfirm为let变量，便于promptPassword里动态赋值
let handleTokenDialogConfirm = async () => {
}

function handleTokenDialogClose() {
  tokenDialogError.value = ''
  document.body.style.overflow = 'scroll'
  return true
}
</script>

// src/webui/FE/src/App.tsx
import React, { useState, useEffect, useCallback } from 'react';
import Sidebar from './components/Sidebar';
import OneBotConfig from './components/OneBotConfig';
import TokenDialog from './components/TokenDialog';
import { ToastContainer, showToast } from './components/Toast';
import { Config, ResConfig } from './types';
import { apiFetch, getToken, setPasswordPromptHandler, setTokenStorage } from './utils/api';
import { Save, Loader2 } from 'lucide-react';

// 默认配置
const defaultConfig: Config = {
  ob11: {
    enable: false,
    token: '',
    enableWs: false,
    wsPort: 3001,
    enableWsReverse: false,
    wsReverseUrls: [],
    enableHttp: false,
    httpPort: 3000,
    enableHttpPost: false,
    enableHttpHeart: false,
    httpPostUrls: [],
    httpSecret: '',
    messagePostFormat: 'array',
    reportSelfMessage: false,
  },
  satori: {
    enable: false,
    port: 5500,
    token: '',
  },
  heartInterval: 30000,
  enableLocalFile2Url: false,
  debug: false,
  log: false,
  autoDeleteFile: false,
  autoDeleteFileSecond: 60,
  musicSignUrl: '',
  msgCacheExpire: 3600,
  receiveOfflineMsg: false,
  onlyLocalhost: true,
  webui: {
    token: '',
  },
};

function App() {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [config, setConfig] = useState<Config>(defaultConfig);
  const [loading, setLoading] = useState(false);
  const [accountInfo, setAccountInfo] = useState<{ nick: string; uin: string } | null>(null);
  const [token, setToken] = useState(getToken() || '');
  const [showPasswordDialog, setShowPasswordDialog] = useState(false);
  const [passwordError, setPasswordError] = useState('');
  const [passwordResolve, setPasswordResolve] = useState<((value: string) => void) | null>(null);

  // 设置密码提示处理器
  useEffect(() => {
    setPasswordPromptHandler(async (tip: string) => {
      return new Promise<string>((resolve) => {
        setPasswordError(tip || '');
        setShowPasswordDialog(true);
        setPasswordResolve(() => resolve);
      });
    });
  }, []);

  // 处理密码确认
  const handlePasswordConfirm = useCallback((password: string) => {
    if (password.trim()) {
      setShowPasswordDialog(false);
      setPasswordError('');
      if (passwordResolve) {
        passwordResolve(password);
        setPasswordResolve(null);
      }
    } else {
      setPasswordError('密码不能为空');
    }
  }, [passwordResolve]);

  // 加载配置
  useEffect(() => {
    const loadConfig = async () => {
      try {
        setLoading(true);
        const response = await apiFetch<ResConfig>('/api/config');
        if (response.success) {
          setConfig(response.data.config);
          setToken(response.data.token);
          setAccountInfo({
            nick: response.data.selfInfo.nick || response.data.selfInfo.nickname || '',
            uin: response.data.selfInfo.uin,
          });
        }
      } catch (error) {
        console.error('Failed to load config:', error);
      } finally {
        setLoading(false);
      }
    };
    loadConfig();
  }, []);

  // 保存配置
  const handleSave = async () => {
    try {
      setLoading(true);
      const response = await apiFetch('/api/config', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token, config }),
      });
      if (response.success) {
        setTokenStorage(token);
        showToast('配置保存成功', 'success');
      } else {
        showToast('保存失败：' + response.message, 'error');
      }
    } catch (error: any) {
      showToast('保存失败：' + error.message, 'error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen">
      <Sidebar activeTab={activeTab} onTabChange={setActiveTab} accountInfo={accountInfo || undefined} />
      
      <main className="flex-1 p-8 overflow-auto">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <div className="mb-8">
            <h2 className="text-3xl font-bold text-white mb-2">
              {activeTab === 'dashboard' && 'Dashboard'}
              {activeTab === 'onebot' && 'OneBot 11 配置'}
              {activeTab === 'satori' && 'Satori 配置'}
              {activeTab === 'other' && '其他配置'}
              {activeTab === 'about' && '关于'}
            </h2>
            <p className="text-white/80">
              {activeTab === 'dashboard' && '欢迎使用 LLOneBot 配置管理系统'}
              {activeTab === 'onebot' && '配置 OneBot 11 协议相关设置'}
              {activeTab === 'satori' && '配置 Satori 协议相关设置'}
              {activeTab === 'other' && '配置全局设置和其他选项'}
              {activeTab === 'about' && '关于 LLOneBot 项目'}
            </p>
          </div>

          {/* Content */}
          {activeTab === 'dashboard' && (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <div className="card p-6 hover:scale-105">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-gray-800">OneBot 11</h3>
                  <span className={`px-3 py-1 rounded-full text-xs font-medium ${
                    config.ob11.enable ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'
                  }`}>
                    {config.ob11.enable ? '已启用' : '未启用'}
                  </span>
                </div>
                <p className="text-sm text-gray-600">OneBot 11 协议配置</p>
                <button
                  onClick={() => setActiveTab('onebot')}
                  className="mt-4 text-blue-600 text-sm font-medium hover:text-blue-700"
                >
                  前往配置 →
                </button>
              </div>

              <div className="card p-6 hover:scale-105">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-gray-800">Satori</h3>
                  <span className={`px-3 py-1 rounded-full text-xs font-medium ${
                    config.satori.enable ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'
                  }`}>
                    {config.satori.enable ? '已启用' : '未启用'}
                  </span>
                </div>
                <p className="text-sm text-gray-600">Satori 协议配置</p>
                <button
                  onClick={() => setActiveTab('satori')}
                  className="mt-4 text-blue-600 text-sm font-medium hover:text-blue-700"
                >
                  前往配置 →
                </button>
              </div>

              <div className="card p-6 hover:scale-105">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-gray-800">系统设置</h3>
                  <span className="px-3 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                    配置
                  </span>
                </div>
                <p className="text-sm text-gray-600">全局配置和系统选项</p>
                <button
                  onClick={() => setActiveTab('other')}
                  className="mt-4 text-blue-600 text-sm font-medium hover:text-blue-700"
                >
                  前往配置 →
                </button>
              </div>
            </div>
          )}

          {activeTab === 'onebot' && (
            <>
              <OneBotConfig
                config={config.ob11}
                onChange={(newOb11Config) => setConfig({ ...config, ob11: newOb11Config })}
              />
              <div className="mt-6 flex justify-end">
                <button
                  onClick={handleSave}
                  disabled={loading}
                  className="btn-primary flex items-center gap-2"
                >
                  {loading ? (
                    <>
                      <Loader2 size={20} className="animate-spin" />
                      保存中...
                    </>
                  ) : (
                    <>
                      <Save size={20} />
                      保存配置
                    </>
                  )}
                </button>
              </div>
            </>
          )}

          {activeTab === 'satori' && (
            <div className="card p-6">
              <h3 className="text-lg font-semibold text-gray-800 mb-4">Satori 协议</h3>
              <div className="space-y-4">
                <div>
                  <label className="flex items-center justify-between mb-2">
                    <span className="text-sm font-medium text-gray-700">启用 Satori</span>
                    <input
                      type="checkbox"
                      checked={config.satori.enable}
                      onChange={(e) => setConfig({
                        ...config,
                        satori: { ...config.satori, enable: e.target.checked }
                      })}
                      className="w-12 h-6 rounded-full bg-gray-300 relative cursor-pointer appearance-none
                        checked:bg-gradient-to-r checked:from-blue-500 checked:to-purple-600
                        transition-colors duration-200 ease-in-out
                        before:content-[''] before:absolute before:top-0.5 before:left-0.5
                        before:w-5 before:h-5 before:rounded-full before:bg-white
                        before:transition-transform before:duration-200
                        checked:before:translate-x-6"
                    />
                  </label>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Satori 端口
                  </label>
                  <input
                    type="number"
                    value={config.satori.port}
                    onChange={(e) => setConfig({
                      ...config,
                      satori: { ...config.satori, port: parseInt(e.target.value) }
                    })}
                    min="1"
                    max="65535"
                    className="input-field"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Satori Token
                  </label>
                  <input
                    type="password"
                    value={config.satori.token}
                    onChange={(e) => setConfig({
                      ...config,
                      satori: { ...config.satori, token: e.target.value }
                    })}
                    placeholder="Satori Token"
                    className="input-field"
                  />
                </div>
              </div>
              <div className="mt-6 flex justify-end">
                <button onClick={handleSave} disabled={loading} className="btn-primary flex items-center gap-2">
                  {loading ? (
                    <>
                      <Loader2 size={20} className="animate-spin" />
                      保存中...
                    </>
                  ) : (
                    <>
                      <Save size={20} />
                      保存配置
                    </>
                  )}
                </button>
              </div>
            </div>
          )}

          {activeTab === 'about' && (
            <div className="space-y-6">
              <div className="card p-6">
                <h3 className="text-lg font-semibold text-gray-800 mb-4">GitHub</h3>
                <a
                  href="https://github.com/LLOneBot/LLOneBot"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:text-blue-700 hover:underline"
                >
                  https://github.com/LLOneBot/LLOneBot
                </a>
              </div>
              <div className="card p-6">
                <h3 className="text-lg font-semibold text-gray-800 mb-4">文档</h3>
                <a
                  href="https://llonebot.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:text-blue-700 hover:underline"
                >
                  https://llonebot.com
                </a>
              </div>
              <div className="card p-6">
                <h3 className="text-lg font-semibold text-gray-800 mb-4">QQ 群</h3>
                <a
                  href="https://qm.qq.com/q/EZndy3xntQ"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-2xl font-bold text-blue-600 hover:text-blue-700 hover:underline"
                >
                  545402644
                </a>
              </div>
            </div>
          )}
        </div>
      </main>

      {/* Loading Overlay */}
      {loading && (
        <div className="fixed inset-0 bg-black/20 flex items-center justify-center z-50">
          <div className="bg-white rounded-2xl p-6 shadow-2xl">
            <Loader2 size={48} className="animate-spin text-blue-600 mx-auto" />
            <p className="mt-4 text-gray-700">加载中...</p>
          </div>
        </div>
      )}

      {/* Password Dialog */}
      <TokenDialog
        visible={showPasswordDialog}
        onConfirm={handlePasswordConfirm}
        error={passwordError}
      />

      {/* Toast Container */}
      <ToastContainer />
    </div>
  );
}

export default App;
